package com.heima.bos.domain.bc;
// Generated 2017-7-17 21:47:49 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Standard generated by hbm2java
 */
@Entity
@Table(name = "bc_standard"
        , catalog = "bos"
)
public class Standard implements java.io.Serializable {


    private Long id;
    private String name;
    private long minweight;
    private long maxweight;
    private long minlength;
    private long maxlength;
    private Date operationtime;
    private String operator;
    private String operatordept;
    private Byte isDel = 0;

    public Standard() {
    }


    public Standard(String name, long minweight, long maxweight, long minlength, long maxlength) {
        this.name = name;
        this.minweight = minweight;
        this.maxweight = maxweight;
        this.minlength = minlength;
        this.maxlength = maxlength;
    }

    public Standard(String name, long minweight, long maxweight, long minlength, long maxlength, Date operationtime, String operator, String operatordept, Byte isDel) {
        this.name = name;
        this.minweight = minweight;
        this.maxweight = maxweight;
        this.minlength = minlength;
        this.maxlength = maxlength;
        this.operationtime = operationtime;
        this.operator = operator;
        this.operatordept = operatordept;
        this.isDel = isDel;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "NAME", nullable = false, length = 40)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "MINWEIGHT", nullable = false, precision = 10, scale = 0)
    public long getMinweight() {
        return this.minweight;
    }

    public void setMinweight(long minweight) {
        this.minweight = minweight;
    }

    @Column(name = "MAXWEIGHT", nullable = false, precision = 10, scale = 0)
    public long getMaxweight() {
        return this.maxweight;
    }

    public void setMaxweight(long maxweight) {
        this.maxweight = maxweight;
    }

    @Column(name = "MINLENGTH", nullable = false, precision = 10, scale = 0)
    public long getMinlength() {
        return this.minlength;
    }

    public void setMinlength(long minlength) {
        this.minlength = minlength;
    }

    @Column(name = "MAXLENGTH", nullable = false, precision = 10, scale = 0)
    public long getMaxlength() {
        return this.maxlength;
    }

    public void setMaxlength(long maxlength) {
        this.maxlength = maxlength;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "OPERATIONTIME", length = 0)
    public Date getOperationtime() {
        return this.operationtime;
    }

    public void setOperationtime(Date operationtime) {
        this.operationtime = operationtime;
    }

    @Column(name = "OPERATOR", length = 40)
    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    @Column(name = "OPERATORDEPT", length = 40)
    public String getOperatordept() {
        return this.operatordept;
    }

    public void setOperatordept(String operatordept) {
        this.operatordept = operatordept;
    }

    @Column(name = "IS_DEL")
    public Byte getIsDel() {
        return this.isDel;
    }

    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }


}


